# Generated by Django 4.2.7 on 2025-10-14 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('motivo', models.TextField()),
                ('diagnostico', models.TextField(blank=True, default='')),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada'), ('reprogramada', 'Reprogramada')], default='programada', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('laboratorio', models.CharField(blank=True, default='', max_length=100)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('tipo', models.CharField(choices=[('Tableta', 'Tableta'), ('Cápsula', 'Cápsula'), ('Jarabe', 'Jarabe'), ('Inyección', 'Inyección'), ('Crema', 'Crema'), ('Otro', 'Otro')], default='Tableta', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, default='', max_length=15)),
                ('direccion', models.TextField(blank=True, default='')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.especialidad')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='M', max_length=1)),
                ('tipo_sangre', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='O+', max_length=3)),
                ('telefono', models.CharField(blank=True, default='', max_length=15)),
                ('correo', models.EmailField(blank=True, default='', max_length=254)),
                ('direccion', models.TextField(blank=True, default='')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=10)),
                ('piso', models.IntegerField(default=1)),
                ('capacidad', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('instrucciones', models.TextField(blank=True, default='')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.consulta')),
            ],
        ),
        migrations.CreateModel(
            name='SeguimientoPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_seguimiento', models.DateField()),
                ('observaciones', models.TextField()),
                ('proxima_cita', models.DateField(blank=True, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('presion_arterial', models.CharField(blank=True, default='', max_length=20)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosis', models.CharField(max_length=100)),
                ('frecuencia', models.CharField(max_length=100)),
                ('duracion', models.CharField(max_length=100)),
                ('instrucciones', models.TextField(blank=True, default='')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.consulta')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.medicamento')),
            ],
        ),
        migrations.AddField(
            model_name='consulta',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.medico'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.paciente'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sala'),
        ),
    ]
