# Generated by Django 4.2.7 on 2025-10-14 21:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tratamiento',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='tratamiento',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='tratamiento',
            name='fecha_inicio',
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='dosis',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='duracion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='medicamento',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='instrucciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
