# Generated by Django 4.2.7 on 2025-10-15 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_tratamiento_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='especialidad',
            options={'verbose_name_plural': 'Especialidades'},
        ),
        migrations.AddField(
            model_name='sala',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sala',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sala',
            name='equipamiento',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sala',
            name='especialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.especialidad'),
        ),
        migrations.AddField(
            model_name='sala',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Ocupada', 'Ocupada'), ('Mantenimiento', 'En Mantenimiento'), ('Limpieza', 'En Limpieza')], default='Disponible', max_length=20),
        ),
        migrations.AddField(
            model_name='sala',
            name='tipo',
            field=models.CharField(choices=[('Consulta', 'Consulta'), ('Emergencia', 'Emergencia'), ('Operaciones', 'Operaciones'), ('Recuperación', 'Recuperación'), ('Exámenes', 'Exámenes'), ('Hospitalización', 'Hospitalización')], default='Consulta', max_length=20),
        ),
    ]
