# Generated by Django 4.2.7 on 2025-10-15 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_paciente_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=17),
        ),
    ]
