# Generated by Django 5.2.7 on 2025-10-15 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_medico_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialidad',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
    ]
