# Generated by Django 5.2.7 on 2025-10-15 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_especialidad_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidad',
            name='descripcion',
            field=models.TextField(blank=True, default='', verbose_name='Descripción'),
        ),
    ]
