# Generated by Django 5.2.7 on 2025-10-15 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_especialidad_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidad',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
    ]
