# Generated by Django 4.2.7 on 2025-10-16 02:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_especialidad_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='receta',
            name='fecha_emision',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='estado',
            field=models.CharField(choices=[('programada', 'Programada'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='programada', max_length=20),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.sala'),
        ),
    ]
